name: Continuous Integration

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: antopilo/nuake-website-web:latest
          build-args: |
            APP_GITHUB_SECRET=${{ secrets.APP_GITHUB_SECRET }}
            APP_GITHUB_ID=${{ secrets.APP_GITHUB_ID }}
            AUTH_TRUST_HOST=true
            NEXTAUTH_URL=https://nuake.antopilo.dev
            NEXT_PUBLIC_NEXT_AUTH_URL=https://nuake.antopilo.dev
