on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure write access to repository contents

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'  # Ensure submodules are checked out
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Update submodules
        run: |
          git submodule update --remote
          
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Update submodule"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}